REPORT zes_program.

*RADIOBUTTON

"-- SEL --------------------------------------------------------------------------

*Vertical
  SELECTION-SCREEN BEGIN OF BLOCK b_1 WITH FRAME TITLE text-003.
  PARAMETERS:
    p_ope1 RADIOBUTTON GROUP rb1 DEFAULT 'X', "Opción 1 y predeterminado
    p_ope2 RADIOBUTTON GROUP rb1,             "Opción 2
    p_ope3 RADIOBUTTON GROUP rb1.             "Opción 3
  SELECTION-SCREEN END OF BLOCK b_1.

*Horizontal
  SELECTION-SCREEN BEGIN OF BLOCK b_2 WITH FRAME TITLE text-001.
  SELECTION-SCREEN BEGIN OF LINE.
  "Operación 1
  PARAMETERS: p_ope4 RADIOBUTTON GROUP rb0 USER-COMMAND r DEFAULT 'X'.
  SELECTION-SCREEN COMMENT 2(10) FOR FIELD p_ope4.
  "Operación 2
  PARAMETERS: p_ope5 RADIOBUTTON GROUP rb0.
  SELECTION-SCREEN COMMENT 14(10) FOR FIELD p_ope5.
  "Operación 3
  PARAMETERS: p_ope6 RADIOBUTTON GROUP rb0.
  SELECTION-SCREEN COMMENT 26(10) FOR FIELD p_ope6.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN END OF BLOCK b_2.